---

- connection: httpapi
  hosts: localhost
  vars:
    host: "{{ host_ip }}"
    username: "ansible"
    password: "{{ lookup('password','passwd') }}"
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
  tasks:
  - name: Configure IPv4 address groups.
    fortios_firewall_addrgrp:
      host:  "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      https: "True"
      state: "present"
      firewall_addrgrp:
        name: "testfwgrp"
        member:
         -
            name: "SSLVPN_TUNNEL_ADDR1"
